### ISSUE TITLE
The system to distribute dishes to categories after the parsing 

### ISSUE THREAD

**Issue by Marina1rina** [AlexandrBursak/cookdrive-sb-gh#7]
**This system will allow the distribution of parsed unassigned dishes to proper categories**

UI
CATEGORY ADMIN button - a link to the category and dishes admin page
Left sidebar - the list of categories with the scroll
Main content area - the list of dishes' images and/or names with some kind of checkbox
ADD  button
![1](https://user-images.githubusercontent.com/33944016/33300563-c73e1a9c-d3f9-11e7-93d7-1a14471ebb18.jpg)

DATA STRUCTURE
List of parsed dishes with no assigned category
? Input data: dishes' names and pictures or just dishes

LOGIC OR FLOW INFO
The user chooses a category -> user chooses unassigned dishes that fall into the chosen category -> add (the chosen items disappear from the list of unassigned dishes and get the proper category ID in the database DISHES table).

**Comment by 4rtHurB** [comment]
I need **30 hours** to implement this task. The task will be completed before **12.12.17**.

**Comment by 4rtHurB** [comment]
Ticket #7 has done.
